## Prerequisites

We will get to the good stuff, coding all the way soon... But before we start, we need to install a couple of software on our machine.

### Hardware

* Operating System: Mac OS X (10.8+), Windows 7+, Ubuntu 12+, CentOS 7+, Fedora 22+
* Memory: At least 4 GB+, preferred 8 GB

### Java Development Kit

We need a JDK 8+ installed on our machine. Latest JDK can downloaded from:

* http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html[Oracle JDK 8]

You can use either Oracle JDK or OpenJDK.

### Maven

* Download Apache Maven from https://maven.apache.org/download.cgi.
* Unzip to a directory of your choice and add it to the `PATH`.

You need maven 3.5+.

### Minishift and OpenShift Client

Minishift provides a way to run Openshift (and so Kubernetes) on your laptop.

1. Download minishift from https://github.com/minishift/minishift/releases
2. Follow the instruction from https://docs.openshift.org/latest/minishift/getting-started/installing.html to install
 it.

Be aware of the prerequisites in term of hypervisor.

At the end of the installation process, you should have the `minishift` executable in your `$PATH`. Then follows the
instructions from https://docs.openshift.org/latest/minishift/getting-started/quickstart.html to start minishift and
access the OpenShift Client (command-line) and console (browser).

### IDE

We recommend you to use an IDE. You can use Eclipse, IntelliJ or Netbeans.

#### No IDE ?

If you don't have an IDE, here are the step to get started with Eclipse.

1. First download Eclipse from https://www.eclipse.org/downloads/[the download page].
2. In the _Eclipse Package_ list, select _Eclipse IDE for Java Developers_. It brings you to a download page with a
`Download` button.
3. Once downloaded, unzip it.
4. In the destination directory, you should find an `Eclipse` binary that you can execute.
5. Eclipse asks you to create a workspace.
6. Once launched, click on the _Workbench_ arrow (top right corner).

### Getting the code

[source]
----
git clone https://github.com/cescoffier/vertx-kubernetes-workshop
----

// TODO To check once done

You can import the code in your IDE as a Maven project. You can refer to your IDE documentation to know how to import Maven projects.

For Eclipse:

1. Click on `File - Import ... - Maven - Existing Maven Projects`
2. Select the location where you cloned the sources
3. Click _Finish_ and wait...

You are going to see a couple of compilation errors. This is because Eclipse does not mark the `src/main/generated`
directories as _source root_ by default. Right-click on `portfolio-service/src/main/generated` and select _Build Path
-> Use as Source Folder_.

TIP: A complete solution is given in the `solution` directory.

### Build

The build is managed using Apache Maven. Compile everything using:

[source]
----
cd vertx-kubernetes-workshop
mvn clean install
----

As said previously, Vert.x does not depend on Apache Maven. You can use any build tool (or even no build tool).

